public  class Addition{
    public static Integer add(Integer num1,Integer num2) {
        // Commit 1
        // commit 2
        // commit 3
        // commit 4
        // commit 5
        // commit 6 by Rishikesh Bagekar
        // commit for addition class
        Integer sum;
        sum=num1+num2;
        System.debug('Addition of '+num1+' and '+num2+' is '+sum);
        return sum;
        //sem value returned
    }
}