# This is a basic workflow to help you get started with Actions

name: First workflow
on: workflow_dispatch

jobs:
  FirstJob:
    runs-on: ubuntu-latest
      steps:
        - name: Print Greeting
          run: echo "Hello World"
        - name1: Print Bye
          run: echo "Good Bye"
          
  
