#comment
name: Second workflow
on: 
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build Job
        run: npm run build
      - name: Deploy job
        run: echo "Builded successfully"

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Parallel run
        run: echo "Hello World"
      - name: Print Bye
        run: |
             echo "Good Bye"
             echo "Good night"
